# Generated by Django 3.2 on 2021-07-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beam_profile_check', '0002_delete_transformview'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'index_page',
            },
        ),
    ]
